export const UI_TYPES = {
	SET_SELECTED_NAV_ID: 'SET_SELECTED_NAV_ID',
	GET_CURRENT_USER: 'GET_CURRENT_USER',
	GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
	GET_CURRENT_USER_FAILURE: 'GET_CURRENT_USER_FAILURE'
};
